/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainlinkOracleSol from "./ChainlinkOracle.sol";
export type { chainlinkOracleSol };
export type { IUniversalOracle } from "./IUniversalOracle";
export type { OracleManager } from "./OracleManager";
export type { RedStoneOracle } from "./RedStoneOracle";
