/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as chainlinkOracleSol from "./ChainlinkOracle.sol";
export { IUniversalOracle__factory } from "./IUniversalOracle__factory";
export { OracleManager__factory } from "./OracleManager__factory";
export { RedStoneOracle__factory } from "./RedStoneOracle__factory";
