/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vaultManagerSol from "./VaultManager.sol";
export type { vaultManagerSol };
import type * as mocks from "./mocks";
export type { mocks };
import type * as oracles from "./oracles";
export type { oracles };
import type * as tokens from "./tokens";
export type { tokens };
export type { PriceOracle } from "./PriceOracle";
export type { SavingsVault } from "./SavingsVault";
