/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPriceOracle__factory } from "./IPriceOracle__factory";
export { VaultManager__factory } from "./VaultManager__factory";
