/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPriceOracleV1 } from "./IPriceOracleV1";
export type { ManualOracleAdapter } from "./ManualOracleAdapter";
