/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPriceOracleV1,
  IPriceOracleV1Interface,
} from "../../../../contracts/oracles/ManualOracleAdapter.sol/IPriceOracleV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPriceOracleV1__factory {
  static readonly abi = _abi;
  static createInterface(): IPriceOracleV1Interface {
    return new Interface(_abi) as IPriceOracleV1Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPriceOracleV1 {
    return new Contract(address, _abi, runner) as unknown as IPriceOracleV1;
  }
}
